In [7]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
# z = x^T w + b
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [8]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x7981d3129cf0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7981d312a350>


In [9]:
# backward pass
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0118, 0.0279, 0.3183],
        [0.0118, 0.0279, 0.3183],
        [0.0118, 0.0279, 0.3183],
        [0.0118, 0.0279, 0.3183],
        [0.0118, 0.0279, 0.3183]])
tensor([0.0118, 0.0279, 0.3183])


In [11]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

# no_grad stops gradient computation
with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [12]:
z = torch.matmul(x, w)+b
# detach stops gradient calculation from specific layer?
# useful for model freezing?
z_det = z.detach()
print(z_det.requires_grad)

False


In [15]:
inp = torch.eye(4, 5, requires_grad=True)
print(inp)
out = (inp+1).pow(2).t()
print(out)
out.backward(torch.ones_like(out), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], requires_grad=True)
tensor([[4., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 4., 1.],
        [1., 1., 1., 4.],
        [1., 1., 1., 1.]], grad_fn=<TBackward0>)
First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
