In [10]:
import torch
import numpy as np







In [11]:
# auto infer data type
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [12]:
# succeeds np arrays
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [13]:
# properties: shape, data type
x_ones = torch.ones_like(x_data) # only reads shape
print(f"Ones Tensor: \n {x_ones} \n")

# use dtype argument to override data type
x_rand = torch.rand_like(x_data, dtype=torch.float) # can't use rand_like on int matrix?
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0833, 0.0164],
        [0.5443, 0.9426]]) 



In [14]:
shape = (2,3,) # 2 row, 3 column
rand_tensor = torch.rand(shape) # randoms
ones_tensor = torch.ones(shape) # all 1
zeros_tensor = torch.zeros(shape) # all 0

# default datatype seems to be float?
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7746, 0.0685, 0.8552],
        [0.8946, 0.9157, 0.7957]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [17]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
# default for rand is float32
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [25]:
# We move our tensor to the GPU if available
# cuda refers to gpu?
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [24]:
tensor = torch.ones(4, 4)
print("First row: " + str(tensor[0])) # can force a 1d tensor of float32 to str type
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)
print("entire matrix: " + str(tensor)) # can force 2d tensor of float32 to str type as well

First row: tensor([1., 1., 1., 1.])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
entire matrix: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [38]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # concatenation, 0 based indexing for dimension
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [45]:
# 3 different ways of matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1) # creating output storage tensor
torch.matmul(tensor, tensor.T, out=y3)



# * refers to element-wise multiplication, not matrix multiplication
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [55]:
agg = tensor.sum() # sum of every element in the tensor (R^d -> 1), dtype is still tensor
print(agg)
agg_item = agg.item() # get the scalar item from tensor
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


In [58]:
print(f"{tensor} \n")
tensor.add_(5) # add 5 to every element, _ stores the change into original tensor
print(tensor)

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]]) 

tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])


In [61]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy() # 1d tensor into 1d numpy array representation, does not create new array
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [63]:
t.add_(1) # since tensor and np arrays stem from same memory, add 1 operation affects both
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


In [71]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n: {n}")
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [72]:
np.add(n, 1, out=n) # numpy does not have add_ operation
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
